// /////////////////////////////////////////////////////////////////////////
// SystemC code automatically generated by hif2sc
// Part of HIFSuite - Version stable
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef M6502__HH
#define M6502__HH

#include <hif_systemc_extensions.hh>
#include <hif_vhdl_ieee_std_logic_unsigned.hh>
#include <stdint.h>
#include <systemc>

class m6502 :
    public sc_core::sc_module
{

public:

    sc_core::sc_in< sc_dt::sc_logic > clk;
    sc_core::sc_out< sc_dt::sc_lv< 16L > > addr;
    sc_core::sc_in< sc_dt::sc_lv< 8L > > datai;
    sc_core::sc_out< sc_dt::sc_lv< 8L > > datao;
    sc_core::sc_in< sc_dt::sc_logic > irq_n;
    sc_core::sc_in< sc_dt::sc_logic > nmi_n;
    sc_core::sc_in< sc_dt::sc_logic > sob_n;
    sc_core::sc_in< sc_dt::sc_logic > res_n;
    sc_core::sc_in< sc_dt::sc_logic > rdy;
    sc_core::sc_out< sc_dt::sc_logic > vpab;
    sc_core::sc_out< sc_dt::sc_logic > sync;
    sc_core::sc_out< sc_dt::sc_logic > we_n;
    sc_core::sc_out< sc_dt::sc_logic > oeb;

    sc_dt::sc_lv< 3L > hif_cone_when();

    sc_dt::sc_logic dataenb;
    sc_dt::sc_logic vpa;
    sc_dt::sc_logic oen;
    sc_dt::sc_lv< 8L > core_areg;
    sc_dt::sc_lv< 8L > core_sreg;
    sc_dt::sc_lv< 8L > core_xreg;
    sc_dt::sc_lv< 8L > core_yreg;
    sc_dt::sc_lv< 8L > core_pch;
    sc_dt::sc_lv< 8L > core_pcl;
    sc_dt::sc_lv< 8L > core_alu_out;
    sc_dt::sc_lv< 8L > core_dreg;
    sc_dt::sc_lv< 8L > core_psr;
    sc_dt::sc_lv< 8L > core_addrh;
    sc_dt::sc_lv< 8L > core_addrl;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_dataol;
    sc_dt::sc_lv< 8L > core_xregl;
    sc_dt::sc_lv< 8L > core_yregl;
    sc_dt::sc_lv< 8L > core_sregl;
    sc_dt::sc_lv< 8L > core_aregl;
    sc_dt::sc_lv< 8L > core_dregl;
    sc_dt::sc_lv< 8L > core_alu_outl;
    sc_dt::sc_lv< 8L > core_pchl;
    sc_dt::sc_lv< 8L > core_pcll;
    sc_dt::sc_lv< 8L > core_psrl;
    sc_core::sc_signal< sc_dt::sc_lv< 12L > > core_alu_ctl;
    sc_dt::sc_lv< 6L > core_alu2op;
    sc_dt::sc_lv< 3L > core_alu_ld;
    sc_dt::sc_lv< 7L > core_rg_load;
    sc_dt::sc_logic core_sreg_up;
    sc_dt::sc_logic core_sreg_cen;
    sc_dt::sc_lv< 7L > core_pc_ctl;
    sc_dt::sc_lv< 2L > core_adl_sel;
    sc_dt::sc_lv< 4L > core_adh_sel;
    sc_dt::sc_lv< 3L > core_domux_sel;
    sc_dt::sc_logic core_reset;
    sc_dt::sc_lv< 8L > core_opcde;
    sc_dt::sc_lv< 8L > core_cycle;
    sc_dt::sc_lv< 8L > core_adhmx_pre_y;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_srg_dataol;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_drg_ido;
    sc_dt::sc_lv< 8L > core_drg_idi;
    sc_dt::sc_logic core_drg_ld;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_arg_ido;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_xrg_ido;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_yrg_ido;
    sc_dt::sc_lv< 8L > core_pc_cntih;
    sc_dt::sc_lv< 8L > core_pc_cntil;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_pc_hreg;
    sc_dt::sc_lv< 8L > core_pc_hreg_in;
    sc_core::sc_signal< sc_dt::sc_lv< 16L > > core_pc_pc;
    sc_dt::sc_lv< 8L > core_adlmx_lreg;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_adlmx_lrg_ido;
    sc_dt::sc_lv< 8L > core_alu_jreg;
    sc_dt::sc_lv< 8L > core_alu_kreg;
    sc_dt::sc_lv< 8L > core_alu_add_b;
    sc_dt::sc_lv< 8L > core_alu_log_b_preinv;
    sc_dt::sc_lv< 8L > core_alu_log_b;
    sc_dt::sc_lv< 8L > core_alu_add_out;
    sc_dt::sc_lv< 8L > core_alu_log_out;
    sc_dt::sc_lv< 8L > core_alu_bcd_out;
    sc_dt::sc_lv< 8L > core_alu_dcd;
    sc_dt::sc_lv< 3L > core_alu_log_ctl;
    sc_dt::sc_lv< 8L > core_alu_alu_outl;
    sc_dt::sc_logic core_alu_add_sub;
    sc_dt::sc_logic core_alu_add_cin;
    sc_dt::sc_logic core_alu_add_cout4;
    sc_dt::sc_logic core_alu_add_cout;
    sc_dt::sc_logic core_alu_alu_cout;
    sc_dt::sc_logic core_alu_log_cin;
    sc_dt::sc_logic core_alu_log_cout;
    sc_dt::sc_logic core_alu_bcd_en;
    sc_dt::sc_logic core_alu_bcd_cout;
    sc_dt::sc_lv< 8L > core_alu_sign_ext;
    sc_dt::sc_logic core_alu_z_flag;
    sc_dt::sc_logic core_alu_n_flag;
    sc_dt::sc_logic core_alu_v_flag;
    sc_dt::sc_logic core_alu_bra_carry;
    sc_dt::sc_lv< 8L > core_alu_adder_b_sub;
    sc_dt::sc_lv< 8L > core_alu_adder_sub_v;
    sc_dt::sc_logic core_alu_adder_cout4l;
    sc_dt::sc_lv< 4L > core_alu_adder_addh_cry;
    sc_dt::sc_lv< 4L > core_alu_adder_addl_cry;
    sc_dt::sc_lv< 4L > core_alu_bcd_bh;
    sc_dt::sc_lv< 4L > core_alu_bcd_bl;
    sc_dt::sc_logic core_alu_bcd_cout4;
    sc_dt::sc_logic core_alu_bcd_cin4l;
    sc_dt::sc_logic core_alu_bcd_cout8;
    sc_dt::sc_logic core_alu_bcd_gnd;
    sc_dt::sc_logic core_alu_bcd_lo_adj;
    sc_dt::sc_logic core_alu_bcd_hi_adj;
    sc_dt::sc_logic core_alu_bcd_lo_adj_sub;
    sc_dt::sc_logic core_alu_bcd_hi_adj_sub;
    sc_dt::sc_lv< 4L > core_alu_bcd_addh_cry_wD091;
    sc_dt::sc_lv< 4L > core_alu_bcd_addl_cry_iV484;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_alu_jrg_ido;
    sc_dt::sc_lv< 8L > core_alu_jrg_idi;
    sc_dt::sc_logic core_alu_jrg_ld;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_alu_krg_ido;
    sc_dt::sc_lv< 8L > core_sm_opcode;
    sc_dt::sc_lv< 8L > core_sm_opcode_in;
    sc_dt::sc_logic core_sm_opcode_ld;
    sc_dt::sc_lv< 8L > core_sm_state;
    sc_dt::sc_lv< 8L > core_sm_state_in;
    sc_dt::sc_logic core_sm_syncl;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_wel_n;
    sc_dt::sc_logic core_sm_we_d_n;
    sc_dt::sc_logic core_sm_pc_load;
    sc_dt::sc_logic core_sm_pc_h_load;
    sc_dt::sc_logic core_sm_pc_cen;
    sc_dt::sc_logic core_sm_pc_sel_datai;
    sc_dt::sc_lv< 2L > core_sm_pc_vec_sel;
    sc_dt::sc_logic core_sm_pcl_alu_ld;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_sm_psrl;
    sc_dt::sc_lv< 8L > core_sm_psrl_var;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_sob_n_f;
    sc_dt::sc_logic core_sm_aregd_load;
    sc_dt::sc_logic core_sm_dregi_load;
    sc_dt::sc_logic core_sm_drego_load;
    sc_dt::sc_logic core_sm_sreg_load;
    sc_dt::sc_logic core_sm_xreg_load;
    sc_dt::sc_logic core_sm_yreg_load;
    sc_dt::sc_logic core_sm_lreg_load;
    sc_dt::sc_logic core_sm_jregi_load;
    sc_dt::sc_logic core_sm_jrego_load;
    sc_dt::sc_logic core_sm_kregi_load;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_z_flag_f;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_branch_carry_f;
    sc_dt::sc_logic core_sm_adh_alu;
    sc_dt::sc_logic core_sm_adh_dreg;
    sc_dt::sc_logic core_sm_adh_zpg;
    sc_dt::sc_logic core_sm_adh_onepg;
    sc_dt::sc_lv< 3L > core_sm_domux_001;
    sc_dt::sc_lv< 3L > core_sm_domux_010;
    sc_dt::sc_lv< 3L > core_sm_domux_011;
    sc_dt::sc_lv< 3L > core_sm_domux_100;
    sc_dt::sc_lv< 3L > core_sm_domux_101;
    sc_dt::sc_lv< 3L > core_sm_domux_110;
    sc_dt::sc_lv< 3L > core_sm_domux_111;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_resetl;
    sc_dt::sc_logic core_sm_interrupt;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_reset_proc;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_nmi_proc;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_irq_proc;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_irq;
    sc_dt::sc_logic core_sm_irq_pend;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_nmi_pend;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_nmi1;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_nmi2;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_addr_carry;
    sc_dt::sc_logic core_sm_imp2psr;
    sc_dt::sc_logic core_sm_imp2tx;
    sc_dt::sc_logic core_sm_imp2inc;
    sc_dt::sc_logic core_sm_imm_1_addr;
    sc_dt::sc_logic core_sm_rel_addr;
    sc_dt::sc_logic core_sm_zpg_1_addr;
    sc_dt::sc_logic core_sm_zpx_1_addr;
    sc_dt::sc_logic core_sm_abs_1_addr;
    sc_dt::sc_logic core_sm_abx_1_addr;
    sc_dt::sc_logic core_sm_aby_1_addr;
    sc_dt::sc_logic core_sm_inx_1_addr;
    sc_dt::sc_logic core_sm_iny_1_addr;
    sc_dt::sc_logic core_sm_ind_1_addr;
    sc_dt::sc_logic core_sm_imm_3_addr;
    sc_dt::sc_logic core_sm_zpg_3_addr;
    sc_dt::sc_logic core_sm_zpx_3_addr;
    sc_dt::sc_logic core_sm_abs_3_addr;
    sc_dt::sc_logic core_sm_abx_3_addr;
    sc_dt::sc_logic core_sm_acc_addr;
    sc_dt::sc_logic core_sm_zpg_rmw_addr;
    sc_dt::sc_logic core_sm_zpx_rmw_addr;
    sc_dt::sc_logic core_sm_abs_rmw_addr;
    sc_dt::sc_logic core_sm_abx_rmw_addr;
    sc_dt::sc_logic core_sm_type1_read;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_type1_calc;
    sc_dt::sc_logic core_sm_type2_read;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_type2_calc;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_type2_write;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_type2_done;
    sc_dt::sc_logic core_sm_type3_read;
    sc_core::sc_signal< sc_dt::sc_logic > core_sm_type3_calc;
    sc_dt::sc_logic core_sm_branch_take;
    sc_dt::sc_logic core_sm_adc_op;
    sc_dt::sc_logic core_sm_lda_op;
    sc_dt::sc_logic core_sm_cmp_op;
    sc_dt::sc_logic core_sm_cpx_op;
    sc_dt::sc_logic core_sm_cpy_op;
    sc_dt::sc_logic core_sm_ora_op;
    sc_dt::sc_logic core_sm_and_op;
    sc_dt::sc_logic core_sm_eor_op;
    sc_dt::sc_logic core_sm_sta_op;
    sc_dt::sc_logic core_sm_sbc_op;
    sc_dt::sc_logic core_sm_asl_op;
    sc_dt::sc_logic core_sm_lsr_op;
    sc_dt::sc_logic core_sm_rol_op;
    sc_dt::sc_logic core_sm_ror_op;
    sc_dt::sc_logic core_sm_inc_op;
    sc_dt::sc_logic core_sm_dec_op;
    sc_dt::sc_logic core_sm_ldx_op;
    sc_dt::sc_logic core_sm_ldy_op;
    sc_dt::sc_logic core_sm_stx_op;
    sc_dt::sc_logic core_sm_sty_op;
    sc_dt::sc_logic core_sm_bit_op;
    sc_dt::sc_logic core_sm_rmb_op;
    sc_dt::sc_logic core_sm_smb_op;
    sc_dt::sc_logic core_sm_bbx_op;
    sc_dt::sc_logic core_sm_stz_op;
    sc_dt::sc_logic core_sm_trb_op;
    sc_dt::sc_logic core_sm_tsb_op;
    sc_dt::sc_lv< 12L > core_sm_alu_ctl_d;
    sc_dt::sc_lv< 2L > core_sm_alu_ctl_bsel;
    sc_dt::sc_logic core_sm_alu_ctl_carry;
    sc_dt::sc_logic core_sm_alu_ctl_bcd;
    sc_dt::sc_lv< 3L > core_sm_alu_ctl_mode;
    sc_dt::sc_logic core_sm_log_b_inv;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_sm_opcd_ido;
    sc_core::sc_signal< sc_dt::sc_lv< 8L > > core_sm_st_ido;

    void hif_cone_core_alu_jrg_ld();


    void hif_cone_core_alu_jrg_idi();


    void hif_cone_core_pc_hreg_in();


    void hif_cone_core_pc_cntil();


    void hif_cone_core_pc_cntih();


    void hif_cone_core_drg_ld();


    void hif_cone_core_drg_idi();


    void hif_cone_core_sm_we_d_n();


    void hif_cone_core_sm_state_in();


    void hif_cone_core_sm_opcode_in();


    void hif_cone_core_sm_alu_ctl_d();


    void hif_cone_core_reset();


    void hif_cone_core_domux_sel();


    void hif_cone_core_sreg_cen();


    void hif_cone_core_sreg_up();


    void hif_cone_core_addrl();


    void hif_cone_core_addrh();


    void hif_cone_vpa();


    void hif_cone_oen();


    void hif_cone_core_sm_opcode_ld();


    void hif_cone_core_pc_ctl();


    void hif_cone_core_rg_load();


    void hif_cone_core_alu_ld();


    void hif_cone_core_psrl();


    void hif_cone_core_pcll();


    void hif_cone_core_pchl();


    void hif_cone_core_aregl();


    void hif_cone_core_sregl();


    void hif_cone_core_yregl();


    void hif_cone_core_xregl();


    void hif_cone_core_sm_bit_op();


    void hif_cone_core_sm_dec_op();


    void hif_cone_core_sm_inc_op();


    void hif_cone_core_sm_ror_op();


    void hif_cone_core_sm_rol_op();


    void hif_cone_core_sm_lsr_op();


    void hif_cone_core_sm_asl_op();


    void hif_cone_core_sm_cpy_op();


    void hif_cone_core_sm_cpx_op();


    void hif_cone_core_sm_cmp_op();


    void hif_cone_core_alu_outl();


    void hif_cone_core_sm_type3_read();


    void hif_cone_core_sm_type2_read();


    void hif_cone_core_sm_type1_read();


    void hif_cone_core_sm_irq_pend();


    void hif_cone_core_sm_interrupt();


    void hif_cone_core_sm_syncl();


    void hif_cone_core_sm_tsb_op();


    void hif_cone_core_sm_trb_op();


    void hif_cone_core_sm_ldy_op();


    void hif_cone_core_sm_ldx_op();


    void hif_cone_core_sm_sbc_op();


    void hif_cone_core_sm_eor_op();


    void hif_cone_core_sm_and_op();


    void hif_cone_core_sm_ora_op();


    void hif_cone_core_sm_lda_op();


    void hif_cone_core_sm_adc_op();


    void hif_cone_core_alu2op();


    void hif_cone_core_sm_abx_rmw_addr();


    void hif_cone_core_sm_abx_3_addr();


    void hif_cone_core_sm_iny_1_addr();


    void hif_cone_core_sm_aby_1_addr();


    void hif_cone_core_sm_abx_1_addr();


    void hif_cone_core_sm_imp2inc();


    void hif_cone_core_sm_imp2tx();


    void hif_cone_core_sm_state();


    void hif_cone_core_sm_opcode();


    void start_of_simulation();


    const sc_core::sc_time core_hif_verilog_timescale_unit;
    const sc_core::sc_time core_hif_verilog_timescale_precision;
    const sc_core::sc_time core_adhmx_hif_verilog_timescale_unit;
    const sc_core::sc_time core_adhmx_hif_verilog_timescale_precision;
    const sc_core::sc_time core_srg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_srg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_drg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_drg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_arg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_arg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_xrg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_xrg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_yrg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_yrg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_pc_hif_verilog_timescale_unit;
    const sc_core::sc_time core_pc_hif_verilog_timescale_precision;
    const sc_core::sc_time core_adlmx_hif_verilog_timescale_unit;
    const sc_core::sc_time core_adlmx_hif_verilog_timescale_precision;
    const sc_core::sc_time core_adlmx_lrg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_adlmx_lrg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_adder_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_adder_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_adder_addh_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_adder_addh_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_adder_addl_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_adder_addl_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_logic_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_logic_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_bcd_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_bcd_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_bcd_addh_hif_verilog_timescale_unit_sM781;
    const sc_core::sc_time core_alu_bcd_addh_hif_verilog_timescale_precision_qt197;
    const sc_core::sc_time core_alu_bcd_addl_hif_verilog_timescale_unit_gl427;
    const sc_core::sc_time core_alu_bcd_addl_hif_verilog_timescale_precision_iO072;
    const sc_core::sc_time core_alu_jrg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_jrg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_alu_krg_hif_verilog_timescale_unit;
    const sc_core::sc_time core_alu_krg_hif_verilog_timescale_precision;
    const sc_core::sc_time core_sm_hif_verilog_timescale_unit;
    const sc_core::sc_time core_sm_hif_verilog_timescale_precision;
    const sc_core::sc_time core_sm_opcd_hif_verilog_timescale_unit;
    const sc_core::sc_time core_sm_opcd_hif_verilog_timescale_precision;
    const sc_core::sc_time core_sm_st_hif_verilog_timescale_unit;
    const sc_core::sc_time core_sm_st_hif_verilog_timescale_precision;
    const sc_core::sc_time domx_hif_verilog_timescale_unit;
    const sc_core::sc_time domx_hif_verilog_timescale_precision;


    SC_HAS_PROCESS( m6502 );

    m6502( sc_core::sc_module_name name_ );
    ~m6502();


private:

    m6502( const m6502 & );
    const m6502& operator= ( const m6502 & );


    void core_srg_process_Az632();
    void core_drg_ff1();
    void core_arg_ff1();
    void core_xrg_ff1();
    void core_yrg_ff1();
    void core_pc_counter();
    void core_adlmx_lrg_ff1();
    void core_alu_jrg_ff1();
    void core_alu_krg_ff1();
    void core_sm_elr();
    void core_sm_misc();
    void core_sm_pipe();
    void core_sm_opcd_ff1();
    void core_sm_st_ff1();
    void domx_process();
    void st_sD609();
    void st_MM489();
    void st_QN827();
    void st_TY100();
    void st_CZ112();
    void st_ez818();


};


#endif

